name: creating  s3 buckets

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    creating_buckets:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4


            - name: Set up aws creds
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                role-to-assume: ${{ secrets.IAM_ROLE }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Initilize terraform
              run: terraform init
              working-directory: terraform

            - name: format document
              run: terraform fmt
              working-directory: terraform

            - name: planning the doc
              env:
                Bucket_name: ${{ secrets.BUCKET_NAME }}
              run: |
               terraform plan \
                   -var="tf_bucket=$BUCKET_NAME"
              working-directory: terraform

            - name: applying the change
              env: 
                TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
              run: terraform apply -auto-approve
              working-directory: terraform

            - name: uploading files to s3 bucket
              env: 
                TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
              run: |
               aws s3 cp --recursive Portfolio-website/ s3://${{ secrets.BUCKET_NAME }}/Portfolio-website/